Document: opencv-slideshow
Title: Debian opencv-slideshow Manual
Author: <insert document author here>
Abstract: This manual describes what opencv-slideshow is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/opencv-slideshow/opencv-slideshow.sgml.gz

Format: postscript
Files: /usr/share/doc/opencv-slideshow/opencv-slideshow.ps.gz

Format: text
Files: /usr/share/doc/opencv-slideshow/opencv-slideshow.text.gz

Format: HTML
Index: /usr/share/doc/opencv-slideshow/html/index.html
Files: /usr/share/doc/opencv-slideshow/html/*.html
